name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  ci:
    uses: predix-sea/predix-platform-ci/.github/workflows/reusable-frontend-ci.yml@main
    with:
      node-version: "20"
      run-e2e: false
    secrets: inherit
